name: accounts
description: "Accounts App."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  excel: ^4.0.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.4.0
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^13.2.2
  path_provider: ^2.0.14
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  flutter_localization: ^0.3.2
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  font_awesome_flutter: any
  sign_in_with_apple: ^7.0.1
  lottie: ^3.3.1
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  rxdart: ^0.28.0
  uuid: ^4.5.1
  qr_flutter: ^4.1.0
  fl_chart: ^1.0.0
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  open_filex: ^4.7.0
  mobile_scanner: ^7.0.1
dependency_overrides:
  intl: ^0.20.2
  archive: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.5.0
  hive_generator: ^2.0.1
  build_runner: any

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  class_name: S
  main_locale: ar



  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/lottie/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
